wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712733636.0
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.16.6
      8:
      - 1
      - 5
      13: linux-x86_64
